version: 1

topics:
  position:
    schema:
      x: int
      y: int

metrics:
  y over time:
    type: test
    query_string: select 'y',timestamp,y from position order by timestamp
    description: y over time
    template_type: system
    template: line
  static value:
    type: batch
    query_string: select 1.234
    template_type: system
    template: scalar
    units: seconds

metrics sets:
  cool metrics:
    metrics:
      - y over time
      - static value
