load("@rules_python//python/entry_points:py_console_script_binary.bzl", "py_console_script_binary")

py_console_script_binary(
    name = "stubgen",
    pkg = "@resim_pkg_deps//mypy",
    visibility = ["//visibility:public"],
)
