comment: # this is a top-level key
  layout: "diff, flags, files"
  behavior: new
  require_changes: false # if true: only post the comment if coverage changes
  require_base: no # [if yes :: must have a base report to post]
  require_head: yes # [if yes :: must have a head report to post]
