site_name: ReSim Open Libraries
site_url: http://resim-docs-prod.s3-website-us-west-1.amazonaws.com
copyright: Copyright &copy; 2023, ReSim, Inc. All rights reserved

docs_dir: docs/resim
site_dir: site_open

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - attr_list
  - pymdownx.details

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

dev_addr: 0.0.0.0:8080

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
      - protobuf

nav:
    - ReSim: 'index.md'
    - Transforms:
      - 'transforms/liegroups.md'
      - 'transforms/using_liegroups.md'
      - 'transforms/liegroup_derivatives.md'
    - Curves: 
      - 'curves/index.md'
      - 'curves/rigid_body_state.md'
    - Math:
      - 'math/gaussian.md'
    - Time:
      - 'time/time.md'
    - Developer Utilities:
      - 'assert/index.md'
      - 'utils/match.md'
      - 'utils/output_parameters.md'
    - Visualization:
      - 'visualization/index.md'

extra_css: [stylesheets/extra.css]
