import numpy
from typing import overload

class Quaternion:
    @overload
    def __init__(self, vector: numpy.ndarray[numpy.float64[4, 1]]) -> None: ...
    @overload
    def __init__(self, w: float, x: float, y: float, z: float) -> None: ...
    def w(self) -> float: ...
    def x(self) -> float: ...
    def y(self) -> float: ...
    def z(self) -> float: ...
