name: "Setup Bazel Cache Auth"
description: "A custom action to setup a .netrc to auth with bazel cache"
inputs:
  bazel_cache_auth_string:
    description: "An auth string to place in .netrc"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Append to .netrc"
      shell: bash
      env:
        AUTH_STR: "${{ inputs.bazel_cache_auth_string }}"
      run: |
        echo "" >> $HOME/.netrc
        echo "machine open-core-bazel-cache.resim.io" >> $HOME/.netrc
        echo "login ocbc" >> $HOME/.netrc
        echo "password ${AUTH_STR}" >> $HOME/.netrc
        echo "" >> $HOME/.netrc
        echo "${#AUTH_STR}"
        chmod 600 $HOME/.netrc