name: Generate Go from Protobuf and Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  generate-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Bazel
      uses: bazelbuild/setup-bazelisk@v1

    # This assumes you already have rules_go and rules_proto set up
    - name: Generate Go files from uuid.proto
      run: bazel build //resim/metrics/proto:metrics_go_proto
      # Replace //path/to:your_proto_go with the actual target in your Bazel BUILD file

    - name: Copy generated files to a directory
      run: |
        mkdir metrics
        cp $(bazel info bazel-bin)/resim/utils/proto/uuid_go_proto_/github.com/resim-ai/open-core/* metrics/
        cp $(bazel info bazel-bin)/resim/metrics/proto/metrics_go_proto_/github.com/resim-ai/open-core/* metrics/

    - name: Archive generated files
      run: tar czf metrics-go.tar.gz -C metrics .

    - uses: ncipollo/release-action@v1.12.0
      with:
        tag: ${{ env.GITHUB_REF_NAME }}
        artifacts: "metrics-go.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Go pkg DB
      run: curl https://sum.golang.org/lookup/github.com/resim-ai/open-core@$GITHUB_REF_NAME
      env:
        GITHUB_REF_NAME: ${{ env.GITHUB_REF_NAME }}
