name: Lint & Generate CodeCov Report
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  coverage:
    name: Lint & Generate Coverage Report
    runs-on: ubuntu-22.04
    container:
      image: public.ecr.aws/resim/core:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bazel Cache Auth
        uses: ./.github/actions/setup-bazel-cache-auth
        with:
          bazel_cache_auth_string: ${{ secrets.BAZEL_CACHE_AUTH_STRING }}

      - name: Build `compile_commands.json` database
        run: bazel run @hedron_compile_commands//:refresh_all

      - name: Workaround for Custom Docker Image
        # Trunk makes use of git and we will get permissions issues (i.e.
        # detected dubious ownership) if we don't make the repo a safe
        # directory.
        run: git config --global --add safe.directory /__w/open-core/open-core

      - name: Generate Coverage Report
        run: bazel coverage ... --combined_report=lcov --java_runtime_version=remotejdk_11 --nocache_test_results --test_tag_filters="-integration" --remote_download_all

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Test py313
        run: bazel test --config=py313 ...

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
