name: Lint & Generate CodeCov Report
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  coverage:
    name: Lint & Generate Coverage Report
    runs-on: ubuntu-20.04
    container:
      image: public.ecr.aws/resim/core:latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bazel Cache Auth
        uses: ./.github/actions/setup-bazel-cache-auth
        with:
          bazel_cache_auth_string: ${{ secrets.BAZEL_CACHE_AUTH_STRING }}

      - name: Quick netrc check
        run: |
          ls -a $HOME
          wc $HOME/.netrc
          awk '{ print length($0) }' $HOME/.netrc
          cat $HOME/.netrc
          sha256sum $HOME/.netrc

