name: Nightly Checks
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  nightly:
    name: Nightly Checks
    runs-on: ubuntu-20.04
    container:
      image: public.ecr.aws/resim/core:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          set-safe-directory: true

      - name: Cache Bazel
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          # This should be redundant on a nightly job but we'll be explicit
          check-mode: all
