name: hello-world
on: 
  push:
    branches:
      - prod/release-**
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World from ${GITHUB_REF#refs/heads/prod/release-}!"
